### ISSUE TITLE
401 при вызове api

### ISSUE THREAD

**Issue by artemylapko** [centrifugal/centrifugo#289]
Александр, здравствуйте. 

Появилась проблема с вызовом апи в новой версии centrifugo. Как я понял из документации: появился обязательный api_key. Но при вызови api сервер отдает 401 ошибку. Как будто ключ не передается.

**docker-compose.yml**
```
centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo
    command: centrifugo -c config.json
    volumes:
      - ${SOURCE_PATH}/${DOCKER_PATH}/apps/centrifugo/config.json:/centrifugo/config.json
    ports:
      - 8000:8000
```

**config.json**
```
{
  "secret": "potato",
  "api_key": "test"
}
```

**Call api for send message**
```
$client = new Client($url, 'test', 'potato');
$client->publish("channel", ["message" => "Hello Everybody"]);
```

**В результате получаю:**
```
Response code: 401
cURL error: 
```

Подскажите, пожалуйста, что я упустил?!

**Comment by FZambia** [comment]
@artemylapko hello! Just tried to reproduce and it works for me. Maybe your volume config path is wrong... Could you show full server logs on Centrifugo start and after making API request?

**Comment by artemylapko** [comment]
@FZambia Big thanks!! My volume config path is correct, but my config path **in the command** is wrong. 

```
centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo
    volumes:
      - ${SOURCE_PATH}/${DOCKER_PATH}/apps/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c centrifugo/config.json
    ports:
      - 8000:8000
```

I replaced the `centrifugo -c config.json` with a `centrifugo -c centrifugo/config.json`
