### ISSUE TITLE
History "not available" for private channels

### ISSUE THREAD

**Issue by cyc60** [centrifugal/centrifugo#290]
## Prerequisites

_Put an `x` in the boxes that apply:_

* [ ] This is a bug report
* [ ] This is a feature request
* [x] This is a question (did you check the [FAQ](https://centrifugal.github.io/centrifugo/faq/) btw?)

## Description
Hello, 
Does history work for user channel boundary or private channel? I receive "not available" response with 108 error code from the admin interface and history method from the centrifuge js library.
For example i tried get history for channels like "private#5", "private$5", 
But it works with "private:5" 

**namespace config**
```
 namespaces:
  - name: private
    anonymous: false
    publish: false
    join_leave: true
    presence: true
    presence_stats: true
    history_size: 50
    history_lifetime: 300
    history_recover: true
```

### Versions

* Centrifugo version is 2.2.2
* Client library used is centrifuge-<???> of version <???>
* Operating system is ubuntu

### And a bit more questions to help diagnoze a bug nature

_Put an `x` in the boxes that apply:_

* [ ] Can you reliably reproduce the problem?
* [x ] Reproduces on latest Centrifugo version?

## Usage information (optional)

Please share some information about your Centrifugo usage. This section will help us to understand how developers work with Centrifugo so we could focus on improving demanded functionality.

_Put an `x` in the boxes that apply:_

* [ ] I am not using Centrifugo yet
* [ ] I am using Centrifugo with Memory engine
* [x ] I am using Centrifugo with Redis engine
* [x ] I am using channel namespaces
* [ ] I am using presence feature
* [x ] I am using history recovery feature
* [ ] I am using SockJS transport
* [x ] I am using Websocket transport only
* [ ] I am using Protobuf client protocol with binary payload in messages
* [ ] I am using GRPC server API
* [ ] I am using connection expiration feature

[Any additional info you want to share - project name, deploy details, etc]
