### ISSUE TITLE
[bug] Docker image: starting container process caused "exec: \"centrifugo\": executable file not found in $PATH": unknown.

### ISSUE THREAD

**Issue by azcoppen** [centrifugal/centrifugo#391]
In any configuration, docket image fails, including any volume you specify.

```
docker run --ulimit nofile=65536:65536 -p 8000:8000 centrifugo/centrifugo centrifugo --admin --web --insecure_admin

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"centrifugo\": executable file not found in $PATH": unknown.

ERRO[0003] error waiting for container: context canceled
```

Or with config file

```
docker run --ulimit nofile=65536:65536 -v /home/me -p 8000:8000 centrifugo/centrifugo centrifugo -c config.json

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused 
"exec: \"centrifugo\": executable file not found in $PATH": unknown.
ERRO[0003] error waiting for container: context canceled
```

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by FZambia** [comment]
Hello, just tried to reproduce – works fine for me:

```
docker run --ulimit nofile=65536:65536 -p 8000:8000 centrifugo/centrifugo:v2.6.2 centrifugo --admin --admin_insecure
{"level":"info","version":"2.6.2","runtime":"go1.14.7","pid":1,"engine":"Memory","gomaxprocs":2,"time":"2020-09-09T05:56:29Z","message":"starting Centrifugo"}
{"level":"info","path":"/centrifugo/config.json","time":"2020-09-09T05:56:29Z","message":"using config file"}
{"level":"warn","time":"2020-09-09T05:56:29Z","message":"consider migrating to offset protocol field, details: https://github.com/centrifugal/centrifugo/releases/tag/v2.5.0"}
{"level":"warn","time":"2020-09-09T05:56:29Z","message":"config file not found"}
{"level":"warn","time":"2020-09-09T05:56:29Z","message":"INSECURE admin mode enabled"}
{"level":"info","time":"2020-09-09T05:56:29Z","message":"serving websocket, SockJS, API, admin endpoints on :8000"}
```

BTW you are using wrong command-line arguments which I suppose have been valid for Centrifugo v1, but not actual anymore for Centrifugo v2.

**Comment by azcoppen** [comment]
@FZambia Thanks chap! I couldn't get it working that way, but i did manage to get an image up and working within Laradock (https://laradock.io/documentation/#add-more-docker-images) using this configuration (`laradock/docker-compose.yml`):

```
### CENTRIFUGO ###################################################
    centrifugo:
      container_name: centrifugo
      image: centrifugo/centrifugo:latest
      restart: always
      environment:
        - CENTRIFUGO_SECRET=secret
        - CENTRIFUGO_ADMIN_PASSWORD=password
        - CENTRIFUGO_ADMIN_SECRET=secret
      ports:
        - "8569:8000"
      command: centrifugo --admin
      networks:
        - backend
```
Laradock's just a suite of docker images in compose format and nothing particularly specialised. Every other container is fine and serving up on specific ports.

Creating the container:

```
docker-compose up -d --force-recreate centrifugo
Recreating centrifugo ... 
Recreating centrifugo ... done
```

Checking it:

```
docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED              STATUS              PORTS                                                                                                                            NAMES
966b818674d1        centrifugo/centrifugo:latest   "centrifugo --admin"     About a minute ago   Up About a minute   0.0.0.0:8569->8000/tcp                                                                                                           centrifugo

```

However, it's not listening on port 8000 (`sudo netstat -peanut | grep ":8000 "` is blank).

```
docker-compose logs centrifugo
Attaching to centrifugo
centrifugo             | {"level":"info","version":"2.6.2","runtime":"go1.14.7","pid":1,"engine":"Memory","gomaxprocs":4,"time":"2020-09-10T02:15:55Z","message":"starting Centrifugo"}
centrifugo             | {"level":"info","path":"/centrifugo/config.json","time":"2020-09-10T02:15:55Z","message":"using config file"}
centrifugo             | {"level":"warn","time":"2020-09-10T02:15:55Z","message":"consider migrating to offset protocol field, details: https://github.com/centrifugal/centrifugo/releases/tag/v2.5.0"}
centrifugo             | {"level":"warn","time":"2020-09-10T02:15:55Z","message":"secret is deprecated, use token_hmac_secret_key instead"}
centrifugo             | {"level":"warn","time":"2020-09-10T02:15:55Z","message":"config file not found"}
centrifugo             | {"level":"info","time":"2020-09-10T02:15:55Z","message":"serving websocket, SockJS, API, admin endpoints on :8000"}
```

Am i missing something in the configuration here? I can see there's no config file but i'm assuming that's not necessary with the environmental variables (these could really be documented as it would be helpful)?

**Comment by FZambia** [comment]
> I can see there's no config file but i'm assuming that's not necessary with the environmental variables (these could really be documented as it would be helpful)?

Yes, it's possible to work without a config file. In this case, you can configure everything over environment variables. All options mentioned in the docs [can be set over env](https://centrifugal.github.io/centrifugo/server/configuration/#configuration-ways) by adding the prefix `CENTRIFUGO_` as you already did for `admin_password` or `admin_secret`.

Maybe it's a bit tricky to configure namespaces array at moment - you should provide valid JSON array string for namespaces as CENTRIFUGO_NAMESPACES environment variable value.

It is better to replace `CENTRIFUGO_SECRET` with `CENTRIFUGO_TOKEN_HMAC_SECRET_KEY` in your configuration (both mean the same but the first one will gone in v3).

**Comment by FZambia** [comment]
@azcoppen have I answered your questions so we can close this issue? Or sth left here?

**Comment by azcoppen** [comment]
@FZambia Still testing. Can't seem to get the server responding on port 8000.

**Comment by azcoppen** [comment]
Still can't bring up the admin screen or connect.

Here's the config:

```
### CENTRIFUGO ###################################################
# https://centrifugal.github.io/centrifugo/server/configuration/#configuration-ways
    centrifugo:
      container_name: centrifugo
      image: centrifugo/centrifugo:latest
      restart: always
      environment:
        - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=secret
        - CENTRIFUGO_ADMIN_PASSWORD=password
        - CENTRIFUGO_ADMIN_SECRET=secret
        - CENTRIFUGO_API_KEY=centrifugo_spi_client
        - CENTRIFUGO_V3_USE_OFFSET=true
        - CENTRIFUGO_LOG_LEVEL=debug
        - CENTRIFUGO_CLIENT_CHANNEL_LIMIT=128
        - CENTRIFUGO_CHANNEL_MAX_LENGTH=255
        - CENTRIFUGO_CLIENT_REQUEST_MAX_SIZE=65536
        - CENTRIFUGO_CLIENT_QUEUE_MAX_SIZE=10485760
        - CENTRIFUGO_CLIENT_ANONYMOUS=FALSE
        - CENTRIFUGO_SOCKJS_HEARTBEAT_DELAY=25
        - CENTRIFUGO_WEBSOCKET_COMPRESSION=FALSE
        - CENTRIFUGO_GOMAXPROCS=0
        - CENTRIFUGO_WEBSOCKET_HANDLER_PREFIX="/connection/websocket"
        - CENTRIFUGO_SOCKJS_HANDLER_PREFIX="/connection/sockjs"
        - CENTRIFUGO_API_HANDLER_PREFIX="/api"
        - CENTRIFUGO_PROMETHEUS_HANDLER_PREFIX="/metrics"
        - CENTRIFUGO_HEALTH_HANDLER_PREFIX="/health"
      ports:
        - "8569:8000"
      command: centrifugo --admin --health
      networks:
        - backend
```

Appears to be working OK:

```
docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                    NAMES
1e0060fffa45        centrifugo/centrifugo:latest   "centrifugo --admin …"   6 minutes ago       Up 3 minutes        0.0.0.0:8569->8000/tcp   centrifugo

```

```
docker-compose logs centrifugo
Attaching to centrifugo
centrifugo             | {"level":"info","version":"2.6.2","runtime":"go1.14.7","pid":1,"engine":"Memory","gomaxprocs":4,"time":"2020-09-15T01:10:11Z","message":"starting Centrifugo"}
centrifugo             | {"level":"info","path":"/centrifugo/config.json","time":"2020-09-15T01:10:11Z","message":"using config file"}
centrifugo             | {"level":"warn","time":"2020-09-15T01:10:11Z","message":"config file not found"}
centrifugo             | {"level":"info","time":"2020-09-15T01:10:11Z","message":"serving websocket, SockJS, API, admin, health endpoints on :8000"}
```

Then....

```
curl -X GET http://127.0.0.1:8000
curl: (7) Failed to connect to 127.0.0.1 port 8000: Connection refused

```
