### ISSUE TITLE
nginx: 768 worker_connections are not enough while connecting to upstream

### ISSUE THREAD

**Issue by applecat** [centrifugal/centrifugo#455]
I've migrated my app to a new server and faced a problem with centrifugo + nginx.

After some time nginx stops serving new requests with error:
`768 worker_connections are not enough while connecting to upstream`

I've increased `worker_connections` number in nginx's settings:
```
events {
        #worker_connections 768;
        worker_connections 1024;
        # multi_accept on;
}
worker_rlimit_nofile 12288;
```
but it only increased time interval between restartings.

After I run `nginx -s reload` I can see suspended processes:
```
$ ps -aux | grep "nginx"
root      584265  0.0  0.0  69556  9104 ?    Ss   11:21   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data  584270  0.0  0.0  70000 14388 ?    S    11:21   0:00 nginx: worker process *is shutting down*
www-data  584275  0.0  0.0  69168 10984 ?    S    11:21   0:00 nginx: worker process *is shutting down*
www-data  587720  3.5  0.1  83860 34640 ?    S    11:35   0:37 nginx: worker process
www-data  587721  0.3  0.0  70640 21120 ?    S    11:35   0:03 nginx: worker process
...
```

```
$ for pid in `pidof nginx`; do echo "$(< /proc/$pid/cmdline)"; egrep 'files|Limit' /proc/$pid/limits; echo "Currently open files: $(ls -1 /proc/$pid/fd | wc -l)"; echo; done

nginx: worker process is shutting down
Limit                     Soft Limit           Hard Limit           Units     
Max open files            12288                12288                files     
Currently open files: 46

nginx: worker process is shutting down
Limit                     Soft Limit           Hard Limit           Units     
Max open files            12288                12288                files     
Currently open files: 84

nginx: worker process is shutting down
Limit                     Soft Limit           Hard Limit           Units     
Max open files            12288                12288                files     
Currently open files: 252

nginx: worker process is shutting down
Limit                     Soft Limit           Hard Limit           Units     
Max open files            12288                12288                files     
Currently open files: 564
...
```

If I stop centrifugo process then nginx starts working just fine.

As I understand, there are hung websocket connections.

Here is my centrifugo config:
```
v3_use_offset: true
token_hmac_secret_key: ...
admin_password: ...
admin_secret: ...
api_key: ...

publish: false     # allow clients to publish messages into channels directly (from client side) (By default it's false)
anonymous: true    # enables anonymous access (with empty user ID in connection parameters). By default false

namespaces:
  - name: auth
    publish: false     # allow clients to publish messages into channels directly (from client side) (By default it's false)
    anonymous: false   # enables anonymous access (with empty user ID in connection parameters). By default false

    history_size: 50
    history_lifetime: 600   # interval in seconds how long to keep channel history messages
    history_recover: true  
```

And here is nginx config:
```
upstream centrifugo_ru {
    ip_hash;
    server 127.0.0.1:8020;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    ...

    location /centrifugo {
        rewrite ^/centrifugo(.*)        $1 break;
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_pass http://centrifugo_ru;
    }

    location /centrifugo/connection {
        rewrite ^/centrifugo(.*)        $1 break;

        proxy_next_upstream error;
        gzip on;
        gzip_min_length 1000;
        gzip_proxied any;
        proxy_buffering off;
        keepalive_timeout 65;
        proxy_pass http://centrifugo_ru;
        proxy_read_timeout 60s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```

I've tried centrifugo 2.8.5 and 2.5.1 (version installed on my previous machine and worked perfect).
Centrigugo runs with docker:
```
docker run --name centrifugo_ru -d --restart always --ulimit nofile=65536:65536 -v /web/site.ru:/centrifugo -p 127.0.0.1:8020:8020 centrifugo/centrifugo:v2.8.5 centrifugo -c centrifugo_config.yaml --log_level=info -p 8020
```
