### ISSUE TITLE
Unable to connect to centrifugo server using docker image and standard exaple from git

### ISSUE THREAD

**Issue by stop4uk** [centrifugal/centrifugo#559]
config.json
```
"token_hmac_secret_key": "627f286d-b0f4-40e6-a8c7-42527e467d98",
"admin_password": "7ec611d9-d86d-4da5-8612-4f74edf9bdcd",
"admin_secret": "6521a9ad-da61-4b62-9e32-a65c7b58428c",
"api_key": "64fbccfd-2eb7-4999-b709-eefaec5e1512",
"allowed_origins": ["*"],
"client_insecure": true,
"anonymous": true,
```

docker-compose.yml
```
centrifugo:
    image: centrifugo/centrifugo:latest
    restart: on-failure
    ports:
      - 8800:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    command: centrifugo --config=config.json --admin --log_level=debug
    volumes:
      - ./docker/centrifugo/config.json:/centrifugo/config.json
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

console log
```
centrifuge config 
Object { debug: true, name: "", version: "", websocket: null, sockjs: null, minRetry: 1000, maxRetry: 20000, timeout: 5000, ping: true, pingInterval: 25000, … }
[utils.js:17:13](webpack://Centrifuge/src/utils.js)
client will connect to websocket endpoint [utils.js:17:13](webpack://Centrifuge/src/utils.js)
subscribing on channel [utils.js:17:13](webpack://Centrifuge/src/utils.js)
start connecting [utils.js:17:13](webpack://Centrifuge/src/utils.js)
Status disconnected -> connecting [utils.js:17:13](webpack://Centrifuge/src/utils.js)
disconnected: connect error true [utils.js:17:13](webpack://Centrifuge/src/utils.js)
Status connecting -> disconnected [utils.js:17:13](webpack://Centrifuge/src/utils.js)
disconnected 
Object { reason: "connect error", reconnect: true }
[index1.html:18:25](http://localhost:10000/index1.html)
reconnect after 1062 milliseconds [utils.js:17:13](webpack://Centrifuge/src/utils.js)
start connecting [utils.js:17:13](webpack://Centrifuge/src/utils.js)
Status disconnected -> connecting
```

index.html
```
const container = document.getElementById('counter');
            const centrifuge = new Centrifuge("ws://localhost:8800/connection/websocket", {debug: true});
            
            centrifuge.on('connect', function(ctx) {
                console.log("connected", ctx);
            });

            centrifuge.on('disconnect', function(ctx) {
                console.log("disconnected", ctx);
            });

            centrifuge.subscribe("channel", function(ctx) {
                container.innerHTML = ctx.data.value;
                document.title = ctx.data.value;
            });

            centrifuge.connect();
```
