### ISSUE TITLE
unexpected HTTP status code: 401

### ISSUE THREAD

**Issue by saschati** [centrifugal/centrifugo#570]
Good afternoon, could you please help me. I don’t know I can see how centrifugo works from the box, I don’t understand that I myself work wrong. I'm using centrifugo:4.0.1 to link js to laravel, butt js code:
```
const centrifuge = new Centrifuge('ws://localhost:8001/connection/websocket', {
    debug: false,
    getToken: async () => {
        const response = await WebSocketApi.jwt() // I receive a jwt token from the backend

        const token = response.data.accessToken;

        return token;
    }
});

centrifuge.on('connected', function(ctx) {
   console.log('Connected:', ctx)
});

centrifuge.on('connecting', function(ctx) {
    console.log('Connecting:', ctx)
});

centrifuge.on('disconnected', function(ctx) {
    console.log('Disconnected:', ctx)
});

centrifuge.on('error', function(ctx) {
    console.log('Error:', ctx)
});

centrifuge.connect();
```
docker-compose:
```
centrifugo:
    image: centrifugo/centrifugo
    volumes:
      - ./api/docker/common/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json --admin
    environment:
      CENTRIFUGO_SECRET: centrifugo_secret
      CENTRIFUGO_ADMIN_PASSWORD: centrifugo_admin_password
      CENTRIFUGO_ADMIN_SECRET: centrifugo_admin_secret
      CENTRIFUGO_API_KEY: secret
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: jPE0aEYwqO5nwXH2omiEQB2A5cIXjcijcjGUuJ2k4jji8DVNNA2IonePfUWDmO1s
    ports:
      - 8001:8001
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.centrifugo.rule=Host(`centrifugo.localhost`)
      - traefik.http.routers.centrifugo.entryPoints=http
      - traefik.http.services.centrifugo.loadBalancer.server.port=80
```
config.json:
```
{
    "port": 8001,
    "engine": "memory",
    "api_key": "secret",
    "allowed_origins": [
        "http://api.localhost",
        "http://localhost",
        "*"
    ],
    "use_client_protocol_v1_by_default": true,
    "proxy_connect_endpoint": "http://api/api/v1/centrifugo/connect",
    "proxy_http_headers": [
        "Origin",
        "User-Agent",
        "Cookie",
        "Authorization",
        "X-Real-Ip",
        "X-Forwarded-For",
        "X-Request-Id"
    ],
    "namespaces": [
        {
            "name": "personal"
        }
    ],
    "allow_user_limited_channels": true,
    "allow_subscribe_for_client": true
}
```
But for some reason on startup I get from centrifugo, I get this error when I try to connect
```
centrifugo_1         | {"level":"info","version":"4.0.1","runtime":"go1.18.5","pid":1,"engine":"memory","gomaxprocs":16,"time":"2022-10-20T14:08:17Z","message":"starting Centrifugo"}
centrifugo_1         | {"level":"info","path":"/centrifugo/config.json","time":"2022-10-20T14:08:17Z","message":"using config file"}
centrifugo_1         | {"level":"info","endpoint":"http://api/api/v1/centrifugo/connect","time":"2022-10-20T14:08:17Z","message":"connect proxy enabled"}
centrifugo_1         | {"level":"info","algorithms":"HS256, HS384, HS512","time":"2022-10-20T14:08:17Z","message":"enabled JWT verifiers"}
centrifugo_1         | {"level":"info","time":"2022-10-20T14:08:17Z","message":"serving websocket, API, admin endpoints on :8001"}
centrifugo_1         | {"level":"error","client":"a5e9de98-5967-420d-9dc3-c125b4000559","error":"unexpected HTTP status code: 401","time":"2022-10-20T14:08:21Z","message":"error proxying connect"}
centrifugo_1         | {"level":"info","client":"a5e9de98-5967-420d-9dc3-c125b4000559","code":100,"command":"id:32 connect:{token:\"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vYXBpLmxvY2FsaG9zdC9hcGkvdjEvand0L3Rva2VuIiwiaWF0IjoxNjY2Mjc0NTg0LCJleHAiOjE2NjYyNzgxODQsIm5iZiI6MTY2NjI3NDU4NCwianRpIjoidGVhT09rYzkxRUtyZUM0biIsInN1YiI6ImNkMGM5NmNiLTI5ZmMtNGI4OS04ZmViLTkxMGEzNDYzMjFjYiIsInBydiI6ImI5MTI3OTk3OGYxMWFhN2JjNTY3MDQ4N2ZmZjAxZTIyODI1M2ZlNDgifQ.8Fj2FfgycMdS6InW1CT3MHZDd3JBOm0WGfY61PM9vVQ\" name:\"js\"}","error":"internal server error","reply":"id:32 error:{code:100 message:\"internal server error\" temporary:true}","user":"","time":"2022-10-20T14:08:21Z","message":"client command error"}

```
and this message doesn't go away until I change the backend, so I can't figure out if it's a backend problem or my configuration. I think my request is not reaching the backend
