### ISSUE TITLE
Are Docker .env vars for history options recognised ?

### ISSUE THREAD

**Issue by alexc-hollywood** [centrifugal/centrifugo#602]
We only ever have one channel (no namespaces), and need to keep the last 20 message history in memory. This is the config we're using, using the docs here: https://centrifugal.dev/docs/server/channels#history_size . 

```yaml
    environment:
      CENTRIFUGO_ALLOWED_ORIGINS: "*"
      CENTRIFUGO_ADMIN: "1"
      CENTRIFUGO_ADDRESS: "0.0.0.0"
      CENTRIFUGO_PORT: 7000 
      CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: ${CENTRIFUGO_TOKEN_HMAC_SECRET_KEY}
      CENTRIFUGO_ADMIN_PASSWORD: ${CENTRIFUGO_ADMIN_PASSWORD}
      CENTRIFUGO_ADMIN_SECRET: ${CENTRIFUGO_ADMIN_SECRET}
      CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_CLIENT_INSECURE: "1"
      CENTRIFUGO_HISTORY_SIZE: 20
      CENTRIFUGO_HISTORY_TTL: "1800s"
      CENTRIFUGO_ALLOW_HISTORY_FOR_SUBSCRIBER: "1"
      CENTRIFUGO_ALLOW_HISTORY_FOR_CLIENT: "1"
      CENTRIFUGO_FORCE_RECOVERY: "1"
```

These vars are correctly set on the container itself:

```json
            "Env": [
                "CENTRIFUGO_HISTORY_SIZE=20",
                "CENTRIFUGO_ALLOW_HISTORY_FOR_CLIENT=1",
                "CENTRIFUGO_HISTORY_TTL=1800s",
                "CENTRIFUGO_FORCE_RECOVERY=1",
                "CENTRIFUGO_ADMIN_PASSWORD=redacted",
                "CENTRIFUGO_API_KEY=redacted",
                "CENTRIFUGO_ALLOW_HISTORY_FOR_SUBSCRIBER=1",
                "CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=redacted",
                "CENTRIFUGO_CLIENT_INSECURE=1",
                "CENTRIFUGO_ADMIN_SECRET=redacted",
                "CENTRIFUGO_ADMIN=1",
                "CENTRIFUGO_PORT=7000",
                "CENTRIFUGO_ALLOWED_ORIGINS=*",
                "CENTRIFUGO_ADDRESS=0.0.0.0",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
```

When we start the container, it errors out with this:

```
2023-01-10T23:49:24.105632764Z {"level":"info","path":"/centrifugo/config.json","time":"2023-01-10T23:49:24Z","message":"using config file"}
2023-01-10T23:49:24.105934054Z {"level":"fatal","time":"2023-01-10T23:49:24Z","message":"error validating config: both history size and history ttl required for history"}
```

Are these options supported?

**Comment by FZambia** [comment]
Hello @alexc-hollywood 

I just tried to run Centrifugo locally:

```
CENTRIFUGO_HISTORY_SIZE=20 CENTRIFUGO_HISTORY_TTL=1800s ./centrifugo
2023-01-11 07:35:34 [INF] starting Centrifugo engine=memory gomaxprocs=12 pid=3505 runtime=go1.19.1 version=0.0.0
2023-01-11 07:35:34 [INF] using config file path=/Users/fz/projects/centrifugal/centrifugo/test/config.json
2023-01-11 07:35:34 [INF] enabled JWT verifiers algorithms="HS256, HS384, HS512"
2023-01-11 07:35:34 [INF] serving websocket, API endpoints on :8000
```

So it works. Then if I remove any of the env vars above then I starting to get the error you showed.

Also tried with:

```
version: "3.9"
services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v4.1.0
    command: centrifugo
    environment:
      CENTRIFUGO_HISTORY_SIZE: "20"
      CENTRIFUGO_HISTORY_TTL: "1800s"
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
```

And `docker compose up`. Works for me.

The same when using `.env`:

```
version: "3.9"
services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v4.1.0
    command: centrifugo
    environment:
      CENTRIFUGO_HISTORY_SIZE: ${CENTRIFUGO_HISTORY_SIZE}
      CENTRIFUGO_HISTORY_TTL: ${CENTRIFUGO_HISTORY_TTL}
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
```

With `.env` content like:

```
CENTRIFUGO_HISTORY_SIZE=20
CENTRIFUGO_HISTORY_TTL=1800s
```

Then if I remove one of the environment variables whether in docker-compose.yaml or in .env file I am getting configuration error.
