### ISSUE TITLE
[bug] grpc reflection not working

### ISSUE THREAD

**Issue by ghstahl** [centrifugal/centrifugo#826]
I use postman to make grpc calls and use reflection on all our internal golang services.  

```Feature Request```: ***Log entire config, with secrets redacted at startup.***

```json
{
  "grpc_api": true,
  "grpc_api_address": "localhost",
  "grpc_api_port": 50051,
  "grpc_api_reflection": true,
  "grpc_api_tls_disable": true,
  "token_jwks_public_endpoint": "http://mock-oauth2-pro:50053/.well-known/jwks",
  "admin_password": "password",
  "admin_secret": "secret",
  "admin": true,
  "api_key": "secret",
  "allowed_origins": ["http://localhost:3000"],
  "engine": "redis",
  "redis_address": ["redis:6379"],
  "namespaces": [
    {
      "name": "connector",
      "presence": true,
      "join_leave": true,
      "history_size": 200,
      "history_ttl": "300h",
      "force_positioning": true,
      "force_recovery": true,
      "allow_subscribe_for_client": true,
      "allow_subscribe_for_anonymous": true,
      "allow_publish_for_subscriber": true,
      "allow_publish_for_anonymous": true,
      "allow_history_for_subscriber": true,
      "allow_history_for_anonymous": true,
      "allow_presence_for_subscriber": true,
      "allow_presence_for_anonymous": true
    },
    {
      "name": "connector_private",
      "presence": true,
      "join_leave": true,
      "history_size": 200,
      "history_ttl": "300h",
      "force_positioning": true,
      "force_recovery": true
    }
  ]
}
```
## Startup Logs
```txt
2024-06-06 09:47:18 {"level":"warn","time":"2024-06-06T16:47:18Z","message":"Centrifugo PRO license not found, run in sandbox mode: max connections 20, max nodes 2, max api rps 5"}
2024-06-06 09:47:18 {"level":"info","version":"5.4.0","release_time":"1717095635","edition":"pro","runtime":"go1.22.3","pid":1,"engine":"redis","gomaxprocs":12,"time":"2024-06-06T16:47:18Z","message":"starting Centrifugo"}
2024-06-06 09:47:18 {"level":"info","owner":"unlicensed","max_connections":20,"max_nodes":2,"max_api_rps":5,"time":"2024-06-06T16:47:18Z","message":"license information"}
2024-06-06 09:47:18 {"level":"info","path":"/centrifugo/config.json","time":"2024-06-06T16:47:18Z","message":"using config file"}
2024-06-06 09:47:18 {"level":"info","time":"2024-06-06T16:47:18Z","message":"serving GRPC API service on localhost:50051"}
2024-06-06 09:47:18 {"level":"info","time":"2024-06-06T16:47:18Z","message":"serving websocket, api, admin endpoints on :8000"}
```
<img width="946" alt="image" src="https://github.com/centrifugal/centrifugo/assets/201257/3117a32c-fd17-4fab-8961-4f12b4654cef">

I can make calls to the ```api/info``` endpoint.  
```curl
curl --location 'http://localhost:8765/api/info' \
--header 'accept;' \
--header 'Accept: application/json' \
--header 'X-API-Key: secret' \
--header 'Content-Type: application/json' \
--data '{}'
```

<img width="796" alt="image" src="https://github.com/centrifugal/centrifugo/assets/201257/94eae7c6-3d97-4a9d-86ff-1f63eda67300">

**Versions**
```
"version":"5.4.0"
```

## Docker-compose services
```yaml
  redis:
    image: redis:${REDIS_VERSION:-7}-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  sentinel:
    image: redis:${REDIS_VERSION:-7}-alpine
    entrypoint:
      - /bin/sh
      - -c
      - |
        redis-server --save "" --appendonly no --port 6380 &
        echo "sentinel monitor mymaster 127.0.0.1 6380 2\n" > sentinel.conf
        redis-server sentinel.conf --sentinel
    ports:
      - "6380:6380"
      - "26379:26379"
  cluster:
    image: redis:${REDIS_VERSION:-7}-alpine
    entrypoint:
      - /bin/sh
      - -c
      - |
        redis-server --port 7000 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7000.conf &
        redis-server --port 7001 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7001.conf &
        redis-server --port 7002 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7002.conf &
        while ! redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 --cluster-yes; do sleep 1; done
        wait
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"

  centrifugo-pro:
    container_name: centrifugo-pro
    image: centrifugo/centrifugo-pro:v5
    volumes:
      - ./configs/centrifugo/config-pro.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8765:8000
      - 50051:50051
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      redis:
        condition: service_healthy
```
