### ISSUE TITLE
Centrifugo v6 roadmap

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#832]
This is an issue to collect information about Centrifugo v6 in one place. There is no date for the release defined yet. This post will be updated.

1. Remove SockJS transport - https://github.com/centrifugal/centrifugo/issues/765
2. Remove Tarantool engine - https://github.com/centrifugal/centrifugo/issues/830
3. Revisit TLS configurations - https://github.com/centrifugal/centrifugo/issues/831
4. Revisit configuration of arrays of objects - https://github.com/centrifugal/centrifugo/issues/841

**Comment by FZambia** [comment]
During last two weeks I was working on Centrifugo v6. The focus in v6 is configuration refactoring - make it unified, structured, more explicit.

In the current state it's becoming very hard to maintain and add new features – so as part of Centrifugo v6 implementing the configuration which is simple to read and extend in code. Also, I want to provide a unified way to set secrets for all entities inside arrays - like inside list of proxies, list of consumers configuration. And a unified config key validation (shown now as warnings on Centrifugo v5 start).

To show one example how config will change, this is what we could have in Centrifugo v5 now:

```json
{
  "token_hmac_secret_key": "XXX",
  "admin_password": "XXX",
  "admin_secret": "XXX",
  "api_key": "XXX",
  "allowed_origins": ["http://localhost:3000"],
  "presence": true,
  "namespaces": [
    {"name": "ns", "presence": true}
  ]
}
```

In Centrifugo v6 becomes:

```json
{
  "client": {
    "token": {
      "hmac_secret_key": "XXX"
    },
    "allowed_origins": [
      "http://localhost:3000"
    ]
  },
  "admin": {
    "password": "XXX",
    "secret": "XXX"
  },
  "http_api": {
    "key": "XXX"
  },
  "channel": {
    "without_namespace": {
      "presence": true
    },
    "namespaces": [
      {
        "name": "ns",
        "presence": true
      }
    ]
  }
}
```

Or in YAML:

```yaml
---
client:
  token:
    hmac_secret_key: XXX
  allowed_origins:
  - http://localhost:3000
admin:
  password: XXX
  secret: XXX
http_api:
  key: XXX
channel:
  without_namespace:
    presence: true
  namespaces:
  - name: ns
    presence: true
```

In the code configuration will be a single readable Go struct instead of manually crafted (using viper key getters) different structs.

**Comment by matsuev** [comment]
Hello @FZambia!

In my custom server (on top of the Centrifuge library) I use this approach to configure outgoing proxy connections. Maybe some of my ideas will seem interesting to you.

**Configure all outgoing connections**
```yaml
# Outgoing connections configuration
connections:
  connection-name-01: # connection name
    nats: # connection type ("nats", "http" or "grpc")
      # options specific for NATS connection
      address:
        - nats://127.0.0.1:4222
        - nats://localhost
      # possible credentials (or nothing if insecure connect)
      jwt-token: "" # priority 0 (if enabled)
      nkey: "" # priority 1 (if enabled) only for NATS
      user: "" # priority 2 (if enabled)
      password: ""
      token: "" # priority 3 (if enabled) only fo NATS

    # TLS configuration (if enabled)
    tls:
      cert: "" # path to cert file
      key: ""
      insecure-skip-verify: false
      server-name: ""
      # other TLS options ...

  connection-name-02:
    grpc:
     # options specific for HTTP connection
      url: grpc://127.0.0.1:12000
      credentials-key: authorization
      credentials-value: qwerty
      # any other options ...
    tls:
    # TLS options ...

  connection-name-03:
    http:
      # options specific for HTTP connection
      url: https://127.0.0.1:8443
      user: alex
      password: qwerty
      # any other options ...
```

**Organize connections to pools**
```yaml
# Proxy connections pool configuration
proxies:
  dev-proxy: # proxy pool name
    timeout: "15s" # default timeout 5s (if not set)
    connections:
      connection-name-01:
        endpoint: dev # for NATS or gRPC it means subject "dev.<method>", may be empty
        priority: 1 # default 0, maximum 255 (uint8), if all priorites equivalent it means "roundrobin"
        timeout: "2s" # overwirte default timeout, if no respond after timeout, call next priority connector
      connection-name-03:
        endpoint: api/dev/proxy # for HTTP it means "<addr>/api/dev/proxy/<method>", may be empty
        priority: 2
        headers:
          - Cookie

  prod-proxy:
    connections:
      connection-name-01:
        endpoint: v1
      connection-name-03:
        endpoint: api/v1/proxy
```

**Define default proxy settings**
```yaml
# Default proxy settings
defaults:
  proxy: # map calls to proxy from poll
    connect: prod-proxy
    refresh: prod-proxy
    rpc: dev-proxy
```

**Define overrides for namespaces**
```yaml
namespace:
  personal:
    history-size: 100
    join-leave: true
    force-join-leave: true
    proxy:
      connect: dev-proxy
      refresh: dev-proxy
      rpc: prod-proxy
```

**Comment by FZambia** [comment]
Thx @matsuev , I guess I found a couple of ideas from your conf to consider:

* nats url is better to be an array on Centrifugo level
* some nats auth options can make sense – but I'll leave this for the future most probably
* I'll try to think whether making entities like `namespaces` or `proxies` a map instead of array can be a good move, but there are considerations I have that the array fits better to not be limited in `name` to be a valid map key in YAML/TOML and thus not break existing configurations. Will try to check whether it's possible without breaking changes.
* Think more on proxy configuration inside the namespace. I want to get rid of `granular_proxy_mode` option – and somehow combine global and granular proxy configurations to work together.  So may be part of this initiative.

But need to stop at some point and find good balance between changes and user difficulties during v5->v6 config migrations.

**Comment by FZambia** [comment]
Another feature of Centrifugo v6 - possibility to get the configuration file with all defaults for all all available configuration options. It will be possible using the command like:

```
centrifugo defaultconfig -c config.json
centrifugo defaultconfig -c config.yaml
centrifugo defaultconfig -c config.toml
```

Also, in dry-run mode it will be posted to STDOUT instead of file:

```
centrifugo defaultconfig -c config.json --dry-run
```

Finally, it's possible to provide this command a base configuration file - so the result will inherit option values from base file and will extend it with defaults for everything else:

```
centrifugo defaultconfig -c config.json --dry-run --base existing_config.json
```

**Comment by FZambia** [comment]
One more feature of Centrifugo v6 – possibility to use separate Redis configurations for broker functionality and for presence management.

**Comment by FZambia** [comment]
Attaching example of full JSON file with default values using the command:

```
centrifugo defaultconfig -c config.sample.json
```
[config.sample.json](https://github.com/user-attachments/files/17179020/config.sample.json)

**Comment by FZambia** [comment]
In addition to `defaultconfig` added `defaultenv` command:

```bash
❯ go run main.go defaultenv
CENTRIFUGO_ADDRESS=""
CENTRIFUGO_ADMIN_ENABLED=false
CENTRIFUGO_ADMIN_EXTERNAL=false
CENTRIFUGO_ADMIN_HANDLER_PREFIX=""
CENTRIFUGO_ADMIN_INSECURE=false
CENTRIFUGO_ADMIN_PASSWORD=""
CENTRIFUGO_ADMIN_SECRET=""
...
```

Which prints all config options as environment vars with default values.

It also supports base config file to inherit values from:

```bash
go run main.go defaultenv -b config.json
```

**Comment by FZambia** [comment]
Here is what I am thinking to do regarding proxy configuration in v6 at this point:

```
client:
  proxy:
    connect:
      enabled: true
      endpoint: ""
    refresh:
      enabled: true
      endpoint: ""
channel:
  proxy:
    publish:
      enabled: true
      endpoint: ""
    subscribe:
      enabled: true
      endpoint: ""
    sub_refresh:
      enabled: true
      endpoint: ""
    subscribe_stream:
      enabled: true
      endpoint: ""
  named_proxies:
    - name: "custom1"
      enabled": true
      endpoint: ""
    - name: "custom2"
      enabled: true
      endpoint: ""
  without_namespace:
    subscribe_proxy_name: "default"
    publish_proxy_name: "default"
  namespaces:
    - name: ns1
      subscribe_proxy_name: "default"
      publish_proxy_name: custom1
    - name: ns2
      subscribe_proxy_name: "default"
      publish_proxy_name: custom2
rpc:
  proxy:
    enabled: true
    endpoint: ""
  named_proxies:
    - name: "custom1"
      enabled": true
      endpoint: ""
  without_namespace:
    rpc_proxy_name: "default"
  namespaces:
    - name: ns1
      rpc_proxy_name: "custom1"
```

Main points:

* No proxy vs granular proxy separation now
* connect and refresh are separated to `client` level, each can be configured with its own set of options.
* channel-related proxy configuration is now on `channel` level, and it will be possible to explicitly set different configuration for each type, which reduces the need to use `named_proxies` in many cases.
* `proxies` -> `named_proxies` - but we still need more granular control for channel namespaces, but now it's clear that only channel related proxies should be set in the array.
* `rpc` proxy is also separated, since rpc does not have any relation to the channel
