### ISSUE TITLE
I can't connect to it via the GRPC proxy.

### ISSUE THREAD

**Issue by alishademan** [centrifugal/centrifugo#923]
I set up the GRPC server on localhost and brought up Centrifugo on Docker using Docker Compose.

Following the example provided [here](https://github.com/centrifugal/examples/tree/master/v3/go_proxy/grpc), I tried to proceed, but the connection is not established, so I can't manage it from the backend.

```
services:
  centrifugo:
    image: centrifugo/centrifugo:latest
    command: centrifugo --config=config.json
    volumes:
      - ./config:/centrifugo/
    ports:
      - "8000:8000"
      - "10000:10000"
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
volumes:
  grafana-storage: {}
  prometheus_data: {}
```
